options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1
  _AR_REPO: cicd-bluegreen-docker
  _SERVICE: cicdbg
  _RUNTIME_SA: projects/$PROJECT_NUMBER/serviceAccounts/$PROJECT_NUMBER-compute@developer.gserviceaccount.com

steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}
      - .

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: decide-color
    entrypoint: bash
    args:
      - -ceu
      - |
        set -euo pipefail
        CURR="$(gcloud run services describe "${_SERVICE}" --region "${_REGION}" \
          --format='value(status.traffic[0].tag)' || true)"
        if [[ "${CURR:-blue}" == "blue" ]]; then NEXT_TAG=green; else NEXT_TAG=blue; fi
        # 這裡用 $$NEXT_TAG，避免被 Cloud Build 當成置換變數
        echo "NEXT_TAG=$$NEXT_TAG" | tee /workspace/next_color

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: deploy-no-traffic
    entrypoint: bash
    args:
      - -ceu
      - |
        set -euo pipefail
        source /workspace/next_color
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}"
        echo "Deploying image: $IMAGE with tag: $$NEXT_TAG (no traffic)"
        gcloud run deploy "${_SERVICE}" \
          --image "${IMAGE}" \
          --region "${_REGION}" \
          --tag "$$NEXT_TAG" \
          --no-traffic \
          --service-account "${_RUNTIME_SA}" \
          --set-env-vars=APP_VERSION="${SHORT_SHA}",APP_COLOR="$$NEXT_TAG"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: hint
    entrypoint: bash
    args:
      - -ceu
      - |
        source /workspace/next_color
        echo "Deployed ${_SERVICE} new revision with tag=$$NEXT_TAG at 0%."
        echo "到 Cloud Run > ${_SERVICE} > Revisions > Tags 複製 $$NEXT_TAG 的 tag URL 測試 /healthz。"

# 想要建置完成自動切 100%，再把下面的步驟取消註解，並同樣使用 $$NEXT_TAG
#  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
#    id: promote-to-100
#    entrypoint: bash
#    args:
#      - -ceu
#      - |
#        source /workspace/next_color
#        gcloud run services update-traffic "${_SERVICE}" \
#          --region "${_REGION}" \
#          --to-tags "$$NEXT_TAG=100"
#        echo "Traffic switched to $$NEXT_TAG=100%"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${SHORT_SHA}
